version: '3.8'

services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345  # пароль для root пользователя
      MYSQL_DATABASE: ems  # название базы данных
    volumes:
      - ./ems-backend/src/main/resources/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Путь для инициализации базы данных
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./ems-backend/
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ems
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_USERNAME=root
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./ems-frontend/
    environment:
      - NODE_ENV=development
    restart: always
    ports:
      - "3000:3000"