apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ikar-zindo-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JEQ0NBVlFDQVFBd0p6RVRNQkVHQTFVRUF3d0thV3RoY2kxNmFXNWtiekVRTUE0R0ExVUVDZ3dIYkdWaApjbTVsY2pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDUwNElOY2dVTkVmazNUCnFlOXBlYlR1ZVlNMW1ObUZaRzlUMFNTajRGUnJWbDJxY1piMXhOeGUrd0VHZndBSXBsdDV4a1BxNENPalZYZ1cKS1FKRVN4WHg2NXJvbWpGMXp4S2FjSXhoVllwV2NvMkZTdzd1cjNpMVpRSUFEMXFjMTh2NTRNNVREMWUzZzN6RwpSMjhRR0V4MkhWNlJRQlFrVUpZMjI1Tmd5Q0NzYS9sSWE5ZnBMamM1WGNDZERBUmMvU3crM1lKZjVrY0ZLZTFVCi9BbFdIem8wNkpyOGxZSVN4elBsdjBxalo4RUNuWkdqK2l5dDZ5M2JIMGRkYURxbFV6Unh5Q2pUamJwNmhaWmwKMUNOTUE0UVhOSUFvVUlXOWlVNFl0U3BTQkVUOFVhUkRCZzliOW5PZzhlTnJjaVdoUVUrejhSTGxWb3p1MWZXOQpKZnFMcjAwQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDVG1CZFkveUd1V2lkRjg0Z1ZlRHFaCmMxVytQZENqTHQ1Y2VUM1FDZ1BUM09BWkhSTnJRNFRzbnRvb1hMUjhMOWhvK216R2kzb0lhUGh1TkhLa1VXY00KVkRFQWtCeVp6UlNmYXhqNzVqY2RhcWt0SnZReGQ4UWRCTnMzclowTzBqYjBUczY0RlhYNnc3SjhlaW8xS3ErSwp2L2pjZlBIbTJXb1lxU0NqVnFHMHliS0J2RVk0dUNwMXlpRUcrSzdETjFMdTZVbFI0dWVSbXRQbUJLWkhxMU9yCnM2SXRjZ21QTWdVeGF2SDNubWdHYU5McVhBNVBoKy9YakRvVGlySkNzSHZRVFRMdjM1WWIwbWQ2VDVoMHhpZ1oKcHFvMWo4cG94Yzk2cjNsMVRVdHhjbjBhY1MxNkJPbENURmRDVHdSbEdZL1dsQklIamY5QVFqbU9mNVhVT1MxTAotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth