apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-be
  template:
    metadata:
      labels:
        app: customer-be
    spec:
      containers:
        - name: customer-be
          image: ikarzindo/kcj-customer-be:latest
          env:
            - name: DATASOURCE_DATABASE_HOST
              value: "mysql"
            - name: DATASOURCE_DATABASE_PORT
              value: "3306"
            - name: DATASOURCE_DATABASE_NAME
              value: "kcj-db"
            - name: DATASOURCE_DATABASE_USERNAME
              value: "root"
            - name: DATASOURCE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: kcj-mysql-db-password
#              value: "Ca3=2q4q+Au=9Ct"
            - name: REST_API_URL
              value: "http://customer-be:8890"
          ports:
            - containerPort: 8890
---
apiVersion: v1
kind: Service
metadata:
  name: customer-be
spec:
  type: LoadBalancer
  selector:
    app: customer-be
  ports:
    - protocol: TCP
      port: 8890
      targetPort: 8890