apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-fe
  template:
    metadata:
      labels:
        app: customer-fe
    spec:
      containers:
        - name: customer-fe
          image: ikarzindo/kcj-customer-fe:latest
          env:
            - name: NODE_ENV
              value: "development"
            - name: REST_API_URL
              value: "http://customer-be:8890"
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-fe
spec:
  type: LoadBalancer
  selector:
    app: customer-fe
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
