apiVersion: v1
kind: Pod
metadata:
  name: kcj-customer-fe
  labels:
    env: prod
    app: main
    tier: frontend
    owner: ikar-zindo
spec:
  containers:
    - name: container-kcj-customer-fe
      image: ikarzindo/kcj-customer-fe:latest
      ports:
        - containerPort: 9000
      env:
        - name: NODE_ENV
          value: "development"

    - name: container-web
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: container-api
      image: tomcat:8.5.38
      ports:
        - containerPort: 8080