server:
  port: 8889

spring:
  main:
    banner-mode: off
  messages:
    basename: ValidationMessages

  datasource:
    url: jdbc:mysql://${DATASOURCE_DATABASE_HOST}:${DATASOURCE_DATABASE_PORT}/${DATASOURCE_DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${DATASOURCE_DATABASE_USERNAME}
    password: ${DATASOURCE_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml